# Generated by Django 4.2.5 on 2023-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_candidate', models.CharField(max_length=20)),
                ('yugam_id', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('college', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='varieties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_no', models.IntegerField()),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
