# Generated by Django 4.2.5 on 2023-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='yugam_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
