# Generated by Django 4.2.5 on 2023-09-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
