# Generated by Django 4.2.5 on 2023-09-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name_of_the_candidate', models.CharField(max_length=20)),
                ('yugam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('mobile', models.BigIntegerField()),
                ('college', models.CharField(max_length=30)),
                ('year_of_study', models.CharField(choices=[('year 1', 'First year'), ('year 2', 'Second year'), ('year 3', 'Third year'), ('year 4', 'Final year')], max_length=10)),
            ],
        ),
    ]
