# Generated by Django 4.2.5 on 2023-09-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
