# Generated by Django 4.2.5 on 2023-09-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name_of_the_candidate', models.CharField(max_length=20, unique=True)),
                ('yugam_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('mobile', models.BigIntegerField()),
                ('college', models.CharField(max_length=30)),
                ('year_of_study', models.CharField(choices=[('year 1', 'First year'), ('year 2', 'Second year'), ('year 3', 'Third year'), ('year 4', 'Final year')], max_length=10)),
                ('events_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.event')),
            ],
        ),
    ]
