# Generated by Django 4.2.5 on 2023-09-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_alter_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='events_name',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
