# Generated by Django 4.2.5 on 2023-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
