# Generated by Django 4.2.5 on 2023-09-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_event_prize_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
