# Generated by Django 4.2.5 on 2023-09-20 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0015_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('name', models.CharField(max_length=20, unique=True)),
                ('yugam_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('mobile', models.BigIntegerField()),
                ('college', models.CharField(max_length=30)),
                ('year_of_study', models.CharField(choices=[('year 1', 'First year'), ('year 2', 'Second year'), ('year 3', 'Third year'), ('year 4', 'Final year')], max_length=10)),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
