# Generated by Django 4.2.5 on 2023-09-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
