# Generated by Django 4.2.5 on 2023-09-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_alter_profile_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
