# Generated by Django 4.2.5 on 2023-10-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0018_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.TimeField(),
        ),
    ]
