# Generated by Django 4.2.5 on 2023-10-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0019_alter_event_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
