# Generated by Django 4.2.5 on 2023-10-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0021_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('registration_fee', models.IntegerField()),
                ('contact_number', models.BigIntegerField()),
                ('duration', models.TimeField()),
                ('venue', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.varieties')),
            ],
        ),
    ]
