# Generated by Django 4.2.5 on 2023-10-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0023_registeration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeration',
            old_name='use',
            new_name='user',
        ),
    ]
