# Generated by Django 4.2.5 on 2023-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0026_alter_profile_user_alter_profile_year_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='proshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
